"""Ajout du champ equipment à Activite

Revision ID: 18b7634f6e33
Revises: 
Create Date: 2025-06-17 13:01:39.013687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18b7634f6e33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipment', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activites', schema=None) as batch_op:
        batch_op.drop_column('equipment')

    # ### end Alembic commands ###
